name: Push JSON Files to GitHub
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH key for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          cd TSKPRIO  # Se placer dans le sous-dossier contenant setup.py
          pip install .

      - name: Add and commit changes
        run: |
          cd TSKPRIO  # Se placer dans le sous-dossier contenant tes fichiers JSON
          git add taches.json planifications.json
          git commit -m "Update JSON files" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          cd TSKPRIO
          git push origin main
