name: Push JSON Files to GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_git:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.name "Jrp-Rogue"
          git config --global user.email "rhogini@gmail.com"
      
      - name: Add and commit changes
        run: |
          git add data.json planifications.json  # Remplacer par les fichiers spécifiques
          git commit -m "Update JSON files" || echo "No changes to commit"
      
      - name: Push changes to GitHub
        run: |
          git push origin main  # Remplacer par la branche correcte si nécessaire
