name: Push JSON Files to GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Jrp-Rogue"
          git config --global user.email "rhogini@gmail.com"

      - name: Install dependencies
        run: |
          cd TSKPRIO  # Navigue dans le sous-dossier
          pip install .  # Installe le projet à partir de setup.py ou pyproject.toml

      - name: Add and commit changes
        run: |
          cd TSKPRIO  # Assure-toi d'être dans le sous-dossier
          git add taches.json planifications.json  # Remplace par tes fichiers spécifiques
          git commit -m "Update JSON files" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          git push origin main  # Assure-toi que la branche est correcte
